// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");

var possibleChars = "12345abcdefghijklmnopqrstuvwxyz";

var possibleCharsLength = possibleChars.length;

function random() {
  var chosenChars = /* array */[];
  for(var _i = 1; _i <= 12; ++_i){
    var chosenIndex = Random.$$int(possibleCharsLength);
    var chosenChar = possibleChars.charAt(chosenIndex);
    chosenChars.push(chosenChar);
  }
  return chosenChars.join("");
}

var Name = /* module */[
  /* possibleChars */possibleChars,
  /* possibleCharsLength */possibleCharsLength,
  /* random */random
];

var Asset = /* module */[];

var TrxId = /* module */[];

var Config = /* module */[];

var Account = /* module */[];

var Action = /* module */[];

exports.Name = Name;
exports.Asset = Asset;
exports.TrxId = TrxId;
exports.Config = Config;
exports.Account = Account;
exports.Action = Action;
/* possibleCharsLength Not a pure module */
