// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos_Js = require("./Eos_Js.js");
var Eos_Chain = require("./Eos_Chain.js");
var Eos_Types = require("./Eos_Types.js");

var accountName = Eos_Types.AccountName[/* fromString */3];

var permissionName = Eos_Types.PermissionName[/* fromString */3];

var tokenName = Eos_Types.TokenName[/* fromString */3];

var tableName = Eos_Types.TableName[/* fromString */3];

var scopeName = Eos_Types.ScopeName[/* fromString */3];

var actionName = Eos_Types.ActionName[/* fromString */3];

var typeName = Eos_Types.TypeName[/* fromString */3];

var MakeOpaqueStringType = Eos_Types.MakeOpaqueStringType;

var MakeOpaqueIntType = Eos_Types.MakeOpaqueIntType;

var MakeChecksum256Type = Eos_Types.MakeChecksum256Type;

var MakeChecksum160Type = Eos_Types.MakeChecksum160Type;

var MakeChecksum512 = Eos_Types.MakeChecksum512;

var MakeNameType = Eos_Types.MakeNameType;

var AccountName = Eos_Types.AccountName;

var PermissionName = Eos_Types.PermissionName;

var TokenName = Eos_Types.TokenName;

var TableName = Eos_Types.TableName;

var ScopeName = Eos_Types.ScopeName;

var ActionName = Eos_Types.ActionName;

var TypeName = Eos_Types.TypeName;

var MakeOpaqueDateType = Eos_Types.MakeOpaqueDateType;

var BlockTimestamp = Eos_Types.BlockTimestamp;

var TimePoint = Eos_Types.TimePoint;

var PublicKey = Eos_Types.PublicKey;

var PrivateKey = Eos_Types.PrivateKey;

var Asset = Eos_Types.Asset;

var asset = Eos_Types.asset;

var MerkleRoot = Eos_Types.MerkleRoot;

var Signature = Eos_Types.Signature;

var BlockId = Eos_Types.BlockId;

var TransactionId = Eos_Types.TransactionId;

var AccountPermission = Eos_Types.AccountPermission;

var Info = Eos_Chain.Info;

var Account = Eos_Chain.Account;

var Transaction = Eos_Chain.Transaction;

var Block = Eos_Chain.Block;

var TableRows = Eos_Chain.TableRows;

var Code = Eos_Chain.Code;

var Js = 0;

var make = Eos_Js.make;

var getInfo = Eos_Js.getInfo;

var getCode = Eos_Js.getCode;

var getTableRows = Eos_Js.getTableRows;

var getTableSingleton = Eos_Js.getTableSingleton;

exports.MakeOpaqueStringType = MakeOpaqueStringType;
exports.MakeOpaqueIntType = MakeOpaqueIntType;
exports.MakeChecksum256Type = MakeChecksum256Type;
exports.MakeChecksum160Type = MakeChecksum160Type;
exports.MakeChecksum512 = MakeChecksum512;
exports.MakeNameType = MakeNameType;
exports.AccountName = AccountName;
exports.PermissionName = PermissionName;
exports.TokenName = TokenName;
exports.TableName = TableName;
exports.ScopeName = ScopeName;
exports.ActionName = ActionName;
exports.TypeName = TypeName;
exports.MakeOpaqueDateType = MakeOpaqueDateType;
exports.BlockTimestamp = BlockTimestamp;
exports.TimePoint = TimePoint;
exports.PublicKey = PublicKey;
exports.PrivateKey = PrivateKey;
exports.Asset = Asset;
exports.asset = asset;
exports.MerkleRoot = MerkleRoot;
exports.Signature = Signature;
exports.BlockId = BlockId;
exports.TransactionId = TransactionId;
exports.AccountPermission = AccountPermission;
exports.Info = Info;
exports.Account = Account;
exports.Transaction = Transaction;
exports.Block = Block;
exports.TableRows = TableRows;
exports.Code = Code;
exports.Js = Js;
exports.make = make;
exports.getInfo = getInfo;
exports.getCode = getCode;
exports.getTableRows = getTableRows;
exports.getTableSingleton = getTableSingleton;
exports.accountName = accountName;
exports.permissionName = permissionName;
exports.tokenName = tokenName;
exports.tableName = tableName;
exports.scopeName = scopeName;
exports.actionName = actionName;
exports.typeName = typeName;
/* Eos_Js Not a pure module */
