// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos_Api = require("./Eos_Api.js");

function getInfo(t) {
  return Eos_Api.thenDecode(Eos_Api.Info[/* decode */0], t.getInfo(true));
}

var Account = /* module */[];

exports.getInfo = getInfo;
exports.Account = Account;
/* Eos_Api Not a pure module */
