// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos_Abi = require("./Eos_Abi.js");
var BigNumber = require("@sagan-software/bs-bignumber/src/BigNumber.js");
var Eos_Types = require("./Eos_Types.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Eosio_System = require("./Eosio_System.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function decode(d) {
  return /* record */[
          /* serverVersion */Json_decode.field("server_version", Eos_Types.ServerVersion[/* decode */0], d),
          /* chainId */Json_decode.field("chain_id", Eos_Types.ChainId[/* decode */0], d),
          /* headBlockNum */Json_decode.field("head_block_num", Eos_Types.BlockNum[/* decode */0], d),
          /* lastIrreversibleBlockNum */Json_decode.field("last_irreversible_block_num", Eos_Types.BlockNum[/* decode */0], d),
          /* lastIrreversibleBlockId */Json_decode.field("last_irreversible_block_id", Eos_Types.BlockId[/* decode */0], d),
          /* headBlockId */Json_decode.field("head_block_id", Eos_Types.BlockId[/* decode */0], d),
          /* headBlockTime */Json_decode.field("head_block_time", Eos_Types.BlockTimestamp[/* decode */0], d),
          /* headBlockProducer */Json_decode.field("head_block_producer", Eos_Types.AccountName[/* decode */0], d),
          /* virtualBlockCpuLimit */Json_decode.field("virtual_block_cpu_limit", Json_decode.$$int, d),
          /* virtualBlockNetLimit */Json_decode.field("virtual_block_net_limit", Json_decode.$$int, d),
          /* blockCpuLimit */Json_decode.field("block_cpu_limit", Json_decode.$$int, d),
          /* blockNetLimit */Json_decode.field("block_net_limit", Json_decode.$$int, d)
        ];
}

function encode(x) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "server_version",
                Eos_Types.ServerVersion[/* encode */1](x[/* serverVersion */0])
              ],
              /* :: */[
                /* tuple */[
                  "chain_id",
                  Eos_Types.ChainId[/* encode */1](x[/* chainId */1])
                ],
                /* :: */[
                  /* tuple */[
                    "head_block_num",
                    Eos_Types.BlockNum[/* encode */1](x[/* headBlockNum */2])
                  ],
                  /* :: */[
                    /* tuple */[
                      "last_irreversible_block_num",
                      Eos_Types.BlockNum[/* encode */1](x[/* lastIrreversibleBlockNum */3])
                    ],
                    /* :: */[
                      /* tuple */[
                        "last_irreversible_block_id",
                        Eos_Types.BlockId[/* encode */1](x[/* lastIrreversibleBlockId */4])
                      ],
                      /* :: */[
                        /* tuple */[
                          "head_block_id",
                          Eos_Types.BlockId[/* encode */1](x[/* headBlockId */5])
                        ],
                        /* :: */[
                          /* tuple */[
                            "head_block_time",
                            Eos_Types.BlockTimestamp[/* encode */1](x[/* headBlockTime */6])
                          ],
                          /* :: */[
                            /* tuple */[
                              "head_block_producer",
                              Eos_Types.AccountName[/* encode */1](x[/* headBlockProducer */7])
                            ],
                            /* :: */[
                              /* tuple */[
                                "virtual_block_cpu_limit",
                                x[/* virtualBlockCpuLimit */8]
                              ],
                              /* :: */[
                                /* tuple */[
                                  "virtual_block_net_limit",
                                  x[/* virtualBlockNetLimit */9]
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "block_cpu_limit",
                                    x[/* blockCpuLimit */10]
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "block_net_limit",
                                      x[/* blockNetLimit */11]
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Info = /* module */[
  /* decode */decode,
  /* encode */encode
];

function limit(x) {
  return /* record */[
          /* used */Json_decode.field("used", BigNumber.decode, x),
          /* available */Json_decode.field("available", BigNumber.decode, x),
          /* max */Json_decode.field("max", BigNumber.decode, x)
        ];
}

function permissionKey(x) {
  return /* record */[
          /* key */Json_decode.field("key", Eos_Types.PublicKey[/* decode */0], x),
          /* weight */Json_decode.field("weight", Json_decode.$$int, x)
        ];
}

function permissionAccount(x) {
  return /* record */[
          /* permission */Json_decode.field("permission", Eos_Types.AccountPermission[/* decode */0], x),
          /* weight */Json_decode.field("weight", Json_decode.$$int, x)
        ];
}

function permissionRequiredAuth(x) {
  return /* record */[
          /* threshold */Json_decode.field("threshold", Json_decode.$$int, x),
          /* keys */Json_decode.field("keys", (function (param) {
                  return Json_decode.array(permissionKey, param);
                }), x),
          /* accounts */Json_decode.field("accounts", (function (param) {
                  return Json_decode.array(permissionAccount, param);
                }), x)
        ];
}

function permission(x) {
  return /* record */[
          /* permName */Json_decode.field("perm_name", Eos_Types.PermissionName[/* decode */0], x),
          /* parent */Json_decode.field("parent", Eos_Types.PermissionName[/* decode */0], x),
          /* requiredAuth */Json_decode.field("required_auth", permissionRequiredAuth, x)
        ];
}

function nullableOption(decoder) {
  return (function (param) {
      return Json_decode.map((function (prim) {
                    if (prim === null) {
                      return undefined;
                    } else {
                      return Js_primitive.some(prim);
                    }
                  }), (function (param) {
                    return Json_decode.nullable(decoder, param);
                  }), param);
    });
}

function t(x) {
  return /* record */[
          /* accountName */Json_decode.field("account_name", Eos_Types.AccountName[/* decode */0], x),
          /* headBlockNum */Json_decode.field("head_block_num", Eos_Types.BlockNum[/* decode */0], x),
          /* headBlockTime */Json_decode.field("head_block_time", Eos_Types.BlockTimestamp[/* decode */0], x),
          /* privileged */Json_decode.field("privileged", Json_decode.bool, x),
          /* lastCodeUpdate */Json_decode.field("last_code_update", Eos_Types.BlockTimestamp[/* decode */0], x),
          /* created */Json_decode.field("created", Eos_Types.BlockTimestamp[/* decode */0], x),
          /* coreLiquidBalance */Json_decode.field("core_liquid_balance", Eos_Types.Asset[/* decode */1], x),
          /* ramQuota */Json_decode.field("ram_quota", BigNumber.decode, x),
          /* netWeight */Json_decode.field("net_weight", BigNumber.decode, x),
          /* cpuWeight */Json_decode.field("cpu_weight", BigNumber.decode, x),
          /* netLimit */Json_decode.field("net_limit", limit, x),
          /* cpuLimit */Json_decode.field("cpu_limit", limit, x),
          /* ramUsage */Json_decode.field("ram_usage", BigNumber.decode, x),
          /* permissions */Json_decode.field("permissions", (function (param) {
                  return Json_decode.array(permission, param);
                }), x),
          /* totalResources */Json_decode.field("total_resources", nullableOption(Eosio_System.UserResources[/* decode */0]), x),
          /* selfDelegatedBandwidth */Json_decode.field("self_delegated_bandwidth", nullableOption(Eosio_System.DelegatedBandwidth[/* decode */0]), x),
          /* voterInfo */Json_decode.field("voter_info", nullableOption(Eosio_System.VoterInfo[/* decode */0]), x)
        ];
}

var Decode = /* module */[
  /* limit */limit,
  /* permissionKey */permissionKey,
  /* permissionAccount */permissionAccount,
  /* permissionRequiredAuth */permissionRequiredAuth,
  /* permission */permission,
  /* nullableOption */nullableOption,
  /* t */t
];

var Account = /* module */[
  /* Decode */Decode,
  /* decode */t
];

var Transaction = /* module */[];

var Block = /* module */[];

function decode$1(decodeRow, d) {
  return /* record */[
          /* rows */Json_decode.field("rows", (function (param) {
                  return Json_decode.array(decodeRow, param);
                }), d),
          /* more */Json_decode.field("more", Json_decode.bool, d)
        ];
}

function map(fn, tableRows) {
  return /* record */[
          /* rows */Belt_Array.map(tableRows[/* rows */0], fn),
          /* more */tableRows[/* more */1]
        ];
}

function singleton(tableRows) {
  return Belt_Array.get(tableRows[/* rows */0], 0);
}

var TableRows = /* module */[
  /* decode */decode$1,
  /* map */map,
  /* singleton */singleton
];

function decode$2(d) {
  return /* record */[
          /* accountName */Json_decode.field("account_name", Eos_Types.AccountName[/* decode */0], d),
          /* codeHash */Json_decode.field("code_hash", Json_decode.string, d),
          /* wast */Json_decode.field("wast", Json_decode.string, d),
          /* wasm */Json_decode.field("wasm", Json_decode.string, d),
          /* abi */Json_decode.optional((function (param) {
                  return Json_decode.field("abi", Eos_Abi.decode, param);
                }), d)
        ];
}

function encode$1(d) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "account_name",
                Eos_Types.AccountName[/* encode */1](d[/* accountName */0])
              ],
              /* :: */[
                /* tuple */[
                  "code_hash",
                  d[/* codeHash */1]
                ],
                /* :: */[
                  /* tuple */[
                    "wast",
                    d[/* wast */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "wasm",
                      d[/* wasm */3]
                    ],
                    /* :: */[
                      /* tuple */[
                        "abi",
                        Belt_Option.getWithDefault(Belt_Option.map(d[/* abi */4], Eos_Abi.encode), null)
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

var Code = /* module */[
  /* decode */decode$2,
  /* encode */encode$1
];

exports.Info = Info;
exports.Account = Account;
exports.Transaction = Transaction;
exports.Block = Block;
exports.TableRows = TableRows;
exports.Code = Code;
/* Eos_Abi Not a pure module */
