// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos_Abi = require("./Eos_Abi.js");
var BigNumber = require("@sagan-software/bs-bignumber/src/BigNumber.js");
var Eos_Types = require("./Eos_Types.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function decode(d) {
  return /* record */[
          /* serverVersion */Json_decode.field("server_version", Json_decode.string, d),
          /* headBlockNum */Json_decode.field("head_block_num", Json_decode.$$int, d),
          /* lastIrreversibleBlockNum */Json_decode.field("last_irreversible_block_num", Json_decode.$$int, d),
          /* lastIrreversibleBlockId */Json_decode.field("last_irreversible_block_id", Eos_Types.BlockId[/* decode */0], d),
          /* headBlockId */Json_decode.field("head_block_id", Eos_Types.BlockId[/* decode */0], d),
          /* headBlockTime */Json_decode.field("head_block_time", Json_decode.date, d),
          /* headBlockProducer */Json_decode.field("head_block_producer", Eos_Types.AccountName[/* decode */0], d),
          /* virtualBlockCpuLimit */Json_decode.field("virtual_block_cpu_limit", BigNumber.decode, d),
          /* virtualBlockNetLimit */Json_decode.field("virtual_block_net_limit", BigNumber.decode, d),
          /* blockCpuLimit */Json_decode.field("block_cpu_limit", BigNumber.decode, d),
          /* blockNetLimit */Json_decode.field("block_net_limit", BigNumber.decode, d)
        ];
}

var Info = /* module */[/* decode */decode];

var Account = /* module */[];

var Transaction = /* module */[];

var Block = /* module */[];

function decode$1(decodeRow, d) {
  return /* record */[
          /* rows */Json_decode.field("rows", (function (param) {
                  return Json_decode.array(decodeRow, param);
                }), d),
          /* more */Json_decode.field("more", Json_decode.bool, d)
        ];
}

function map(fn, tableRows) {
  return /* record */[
          /* rows */Belt_Array.map(tableRows[/* rows */0], fn),
          /* more */tableRows[/* more */1]
        ];
}

function singleton(tableRows) {
  return Belt_Array.get(tableRows[/* rows */0], 0);
}

var TableRows = /* module */[
  /* decode */decode$1,
  /* map */map,
  /* singleton */singleton
];

function decode$2(d) {
  return /* record */[
          /* accountName */Json_decode.field("account_name", Eos_Types.AccountName[/* decode */0], d),
          /* codeHash */Json_decode.field("code_hash", Json_decode.string, d),
          /* wast */Json_decode.field("wast", Json_decode.string, d),
          /* wasm */Json_decode.field("wasm", Json_decode.string, d),
          /* abi */Json_decode.optional((function (param) {
                  return Json_decode.field("abi", Eos_Abi.decode, param);
                }), d)
        ];
}

function encode(d) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "account_name",
                Eos_Types.AccountName[/* encode */1](d[/* accountName */0])
              ],
              /* :: */[
                /* tuple */[
                  "code_hash",
                  d[/* codeHash */1]
                ],
                /* :: */[
                  /* tuple */[
                    "wast",
                    d[/* wast */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "wasm",
                      d[/* wasm */3]
                    ],
                    /* :: */[
                      /* tuple */[
                        "abi",
                        Belt_Option.getWithDefault(Belt_Option.map(d[/* abi */4], Eos_Abi.encode), null)
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

var Code = /* module */[
  /* decode */decode$2,
  /* encode */encode
];

exports.Info = Info;
exports.Account = Account;
exports.Transaction = Transaction;
exports.Block = Block;
exports.TableRows = TableRows;
exports.Code = Code;
/* Eos_Abi Not a pure module */
