// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var BigNumber = require("@sagan-software/bs-bignumber/src/BigNumber.js");
var Eos_Types = require("./Eos_Types.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var BignumberJs = require("bignumber.js/bignumber.js");

function decode(x) {
  return /* record */[
          /* maxBlockNetUsage */Json_decode.field("max_block_net_usage", BigNumber.decode, x),
          /* targetBlockNetUsagePct */Json_decode.field("target_block_net_usage_pct", BigNumber.decode, x),
          /* maxTransactionNetUsage */Json_decode.field("max_transaction_net_usage", BigNumber.decode, x),
          /* basePerTransactionNetUsage */Json_decode.field("base_per_transaction_net_usage", BigNumber.decode, x),
          /* netUsageLeeway */Json_decode.field("net_usage_leeway", BigNumber.decode, x),
          /* contextFreeDiscountNetUsageNum */Json_decode.field("context_free_discount_net_usage_num", BigNumber.decode, x),
          /* contextFreeDiscountNetUsageDen */Json_decode.field("context_free_discount_net_usage_den", BigNumber.decode, x),
          /* maxBlockCpuUsage */Json_decode.field("max_block_cpu_usage", BigNumber.decode, x),
          /* targetBlockCpuUsagePct */Json_decode.field("target_block_cpu_usage_pct", BigNumber.decode, x),
          /* maxTransactionCpuUsage */Json_decode.field("max_transaction_cpu_usage", BigNumber.decode, x),
          /* minTransactionCpuUsage */Json_decode.field("min_transaction_cpu_usage", BigNumber.decode, x),
          /* maxTransactionLifetime */Json_decode.field("max_transaction_lifetime", BigNumber.decode, x),
          /* deferredTrxExpirationWindow */Json_decode.field("deferred_trx_expiration_window", BigNumber.decode, x),
          /* maxTransactionDelay */Json_decode.field("max_transaction_delay", BigNumber.decode, x),
          /* maxInlineActionSize */Json_decode.field("max_inline_action_size", BigNumber.decode, x),
          /* maxInlineActionDepth */Json_decode.field("max_inline_action_depth", BigNumber.decode, x),
          /* maxAuthorityDepth */Json_decode.field("max_authority_depth", BigNumber.decode, x),
          /* maxRamSize */Json_decode.field("max_ram_size", BigNumber.decode, x),
          /* totalRamBytesReserved */Json_decode.field("total_ram_bytes_reserved", BigNumber.decode, x),
          /* totalRamStake */Json_decode.field("total_ram_stake", BigNumber.decode, x),
          /* lastProducerScheduleUpdate */Json_decode.field("last_producer_schedule_update", Eos_Types.BlockTimestamp[/* decode */0], x),
          /* lastPerVoteBucketFill */Json_decode.field("last_pervote_bucket_fill", Eos_Types.TimePoint[/* decode */0], x),
          /* perVoteBucket */Json_decode.field("pervote_bucket", BigNumber.decode, x),
          /* perBlockBucket */Json_decode.field("perblock_bucket", BigNumber.decode, x),
          /* totalUnpaidBlocks */Json_decode.field("total_unpaid_blocks", BigNumber.decode, x),
          /* totalActivatedStake */Json_decode.field("total_activated_stake", BigNumber.decode, x),
          /* threshActivatedStakeTime */Json_decode.field("thresh_activated_stake_time", Eos_Types.TimePoint[/* decode */0], x),
          /* lastProducerScheduleSize */Json_decode.field("last_producer_schedule_size", BigNumber.decode, x),
          /* totalProducerVoteWeight */Json_decode.field("total_producer_vote_weight", BigNumber.decode, x),
          /* lastNameClose */Json_decode.field("last_name_close", Eos_Types.BlockTimestamp[/* decode */0], x)
        ];
}

var GlobalState = /* module */[/* decode */decode];

function decode$1(j) {
  return /* record */[
          /* owner */Json_decode.field("owner", Eos_Types.AccountName[/* decode */0], j),
          /* totalVotes */Json_decode.field("total_votes", BigNumber.decode, j),
          /* producerKey */Json_decode.field("producer_key", Json_decode.string, j),
          /* isActive */Json_decode.field("is_active", (function (param) {
                  return Json_decode.map((function (x) {
                                return x === 1;
                              }), Json_decode.$$int, param);
                }), j),
          /* url */Json_decode.field("url", Json_decode.string, j),
          /* unpaidBlocks */Json_decode.field("unpaid_blocks", BigNumber.decode, j),
          /* lastClaimTime */Json_decode.field("last_claim_time", Eos_Types.TimePoint[/* decode */0], j),
          /* location */Json_decode.field("location", Json_decode.$$int, j)
        ];
}

function encode(d) {
  var match = d[/* isActive */3];
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "owner",
                Eos_Types.AccountName[/* encode */1](d[/* owner */0])
              ],
              /* :: */[
                /* tuple */[
                  "total_votes",
                  BigNumber.encode(d[/* totalVotes */1])
                ],
                /* :: */[
                  /* tuple */[
                    "producer_key",
                    d[/* producerKey */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "is_active",
                      match ? 1 : 0
                    ],
                    /* :: */[
                      /* tuple */[
                        "url",
                        d[/* url */4]
                      ],
                      /* :: */[
                        /* tuple */[
                          "unpaid_blocks",
                          BigNumber.encode(d[/* unpaidBlocks */5])
                        ],
                        /* :: */[
                          /* tuple */[
                            "last_claim_time",
                            Eos_Types.TimePoint[/* encode */1](d[/* lastClaimTime */6])
                          ],
                          /* :: */[
                            /* tuple */[
                              "location",
                              d[/* location */7]
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var ProducerInfo = /* module */[
  /* decode */decode$1,
  /* encode */encode
];

function decode$2(x) {
  var partial_arg = Eos_Types.AccountName[/* decode */0];
  return /* record */[
          /* owner */Json_decode.field("owner", Eos_Types.AccountName[/* decode */0], x),
          /* proxy */Json_decode.field("proxy", Eos_Types.AccountName[/* decode */0], x),
          /* producers */Json_decode.field("producers", (function (param) {
                  return Json_decode.array(partial_arg, param);
                }), x),
          /* staked */Json_decode.field("staked", BigNumber.decode, x),
          /* lastVoteWeight */Json_decode.field("last_vote_weight", BigNumber.decode, x),
          /* proxiedVoteWeight */Json_decode.field("proxied_vote_weight", BigNumber.decode, x),
          /* isProxy */Json_decode.field("is_proxy", (function (param) {
                  return Json_decode.map((function (x) {
                                return x === 1;
                              }), Json_decode.$$int, param);
                }), x)
        ];
}

var VoterInfo = /* module */[/* decode */decode$2];

function decode$3(x) {
  return /* record */[
          /* owner */Json_decode.field("owner", Eos_Types.AccountName[/* decode */0], x),
          /* netWeight */Json_decode.field("net_weight", Eos_Types.Asset[/* decode */1], x),
          /* cpuWeight */Json_decode.field("cpu_weight", Eos_Types.Asset[/* decode */1], x),
          /* ramBytes */Json_decode.field("ram_bytes", BigNumber.decode, x)
        ];
}

var UserResources = /* module */[/* decode */decode$3];

function decode$4(x) {
  return /* record */[
          /* from */Json_decode.field("from", Eos_Types.AccountName[/* decode */0], x),
          /* to_ */Json_decode.field("to", Eos_Types.AccountName[/* decode */0], x),
          /* netWeight */Json_decode.field("net_weight", Eos_Types.Asset[/* decode */1], x),
          /* cpuWeight */Json_decode.field("cpu_weight", Eos_Types.Asset[/* decode */1], x)
        ];
}

var DelegatedBandwidth = /* module */[/* decode */decode$4];

var Connector = /* module */[];

var ExchangeState = /* module */[];

var RefundRequest = /* module */[];

var NameBidInfo = /* module */[];

function estimateProducerVotePay(producerInfo, globalState) {
  var perVoteBucket = globalState[/* perVoteBucket */22];
  var totalVotes = producerInfo[/* totalVotes */1];
  var totalProducerVoteWeight = globalState[/* totalProducerVoteWeight */28];
  var producerPerVotePay = perVoteBucket.times(totalVotes).div(totalProducerVoteWeight);
  var minPerVoteDailyPay = new BignumberJs(1000000);
  var match = producerPerVotePay.lt(minPerVoteDailyPay);
  if (match) {
    return new BignumberJs(0);
  } else {
    return producerPerVotePay.div(10000);
  }
}

function estimateProducerBlockPay(producerInfo, globalState) {
  var perBlockBucket = globalState[/* perBlockBucket */23];
  var unpaidBlocks = producerInfo[/* unpaidBlocks */5];
  var totalUnpaidBlocks = globalState[/* totalUnpaidBlocks */24];
  return perBlockBucket.times(unpaidBlocks).div(totalUnpaidBlocks).div(10000);
}

function estimateProducerPay(producerInfo, globalState) {
  var votePay = estimateProducerVotePay(producerInfo, globalState);
  var blockPay = estimateProducerBlockPay(producerInfo, globalState);
  return votePay.plus(blockPay);
}

exports.GlobalState = GlobalState;
exports.ProducerInfo = ProducerInfo;
exports.VoterInfo = VoterInfo;
exports.UserResources = UserResources;
exports.DelegatedBandwidth = DelegatedBandwidth;
exports.Connector = Connector;
exports.ExchangeState = ExchangeState;
exports.RefundRequest = RefundRequest;
exports.NameBidInfo = NameBidInfo;
exports.estimateProducerVotePay = estimateProducerVotePay;
exports.estimateProducerBlockPay = estimateProducerBlockPay;
exports.estimateProducerPay = estimateProducerPay;
/* BigNumber Not a pure module */
