// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos = require("./Eos.js");
var Eosio_System = require("./Eosio_System.js");

var arg = Eosio_System.GlobalState[/* decode */0];

var arg$1 = Eos.accountName("eosio");

var arg$2 = Eos.accountName("eosio");

var arg$3 = Eos.tableName("global");

function getGlobalState(param) {
  return (function (param$1, param$2) {
      return Eos.getTableSingleton(param, arg, arg$1, arg$2, arg$3, param$1, param$2);
    });
}

var arg$4 = Eosio_System.ProducerInfo[/* decode */0];

var arg$5 = Eos.accountName("eosio");

var arg$6 = Eos.accountName("eosio");

var arg$7 = Eos.tableName("producers");

function getProducers(param) {
  return (function (param$1, param$2, param$3, param$4, param$5, param$6) {
      return Eos.getTableRows(param, arg$4, arg$5, arg$6, arg$7, param$1, param$2, param$3, param$4, param$5, param$6);
    });
}

var arg$8 = Eosio_System.VoterInfo[/* decode */0];

var arg$9 = Eos.accountName("eosio");

var arg$10 = Eos.accountName("eosio");

var arg$11 = Eos.tableName("voters");

function getVoters(param) {
  return (function (param$1, param$2, param$3, param$4, param$5, param$6) {
      return Eos.getTableRows(param, arg$8, arg$9, arg$10, arg$11, param$1, param$2, param$3, param$4, param$5, param$6);
    });
}

var System = 0;

var Token = 0;

exports.System = System;
exports.Token = Token;
exports.getGlobalState = getGlobalState;
exports.getProducers = getProducers;
exports.getVoters = getVoters;
/* arg Not a pure module */
