// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos = require("./Eos.js");
var BigNumber = require("@sagan-software/bs-bignumber/src/BigNumber.js");
var Eos_Types = require("./Eos_Types.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function decode(x) {
  return /* record */[
          /* maxBlockNetUsage */Json_decode.field("max_block_net_usage", Json_decode.$$int, x),
          /* targetBlockNetUsagePct */Json_decode.field("target_block_net_usage_pct", Json_decode.$$int, x),
          /* maxTransactionNetUsage */Json_decode.field("max_transaction_net_usage", Json_decode.$$int, x),
          /* basePerTransactionNetUsage */Json_decode.field("base_per_transaction_net_usage", Json_decode.$$int, x),
          /* netUsageLeeway */Json_decode.field("net_usage_leeway", Json_decode.$$int, x),
          /* contextFreeDiscountNetUsageNum */Json_decode.field("context_free_discount_net_usage_num", Json_decode.$$int, x),
          /* contextFreeDiscountNetUsageDen */Json_decode.field("context_free_discount_net_usage_den", Json_decode.$$int, x),
          /* maxBlockCpuUsage */Json_decode.field("max_block_cpu_usage", Json_decode.$$int, x),
          /* targetBlockCpuUsagePct */Json_decode.field("target_block_cpu_usage_pct", Json_decode.$$int, x),
          /* maxTransactionCpuUsage */Json_decode.field("max_transaction_cpu_usage", Json_decode.$$int, x),
          /* minTransactionCpuUsage */Json_decode.field("min_transaction_cpu_usage", Json_decode.$$int, x),
          /* maxTransactionLifetime */Json_decode.field("max_transaction_lifetime", Json_decode.$$int, x),
          /* deferredTrxExpirationWindow */Json_decode.field("deferred_trx_expiration_window", Json_decode.$$int, x),
          /* maxTransactionDelay */Json_decode.field("max_transaction_delay", Json_decode.$$int, x),
          /* maxInlineActionSize */Json_decode.field("max_inline_action_size", Json_decode.$$int, x),
          /* maxInlineActionDepth */Json_decode.field("max_inline_action_depth", Json_decode.$$int, x),
          /* maxAuthorityDepth */Json_decode.field("max_authority_depth", Json_decode.$$int, x),
          /* maxRamSize */Json_decode.field("max_ram_size", BigNumber.decode, x),
          /* totalRamBytesReserved */Json_decode.field("total_ram_bytes_reserved", BigNumber.decode, x),
          /* totalRamStake */Json_decode.field("total_ram_stake", BigNumber.decode, x),
          /* lastProducerScheduleUpdate */Json_decode.field("last_producer_schedule_update", Eos_Types.BlockTimestamp[/* decode */0], x),
          /* lastPerVoteBucketFill */Json_decode.field("last_pervote_bucket_fill", Eos_Types.TimePoint[/* decode */0], x),
          /* perVoteBucket */Json_decode.field("pervote_bucket", Json_decode.$$int, x),
          /* perBlockBucket */Json_decode.field("perblock_bucket", Json_decode.$$int, x),
          /* totalUnpaidBlocks */Json_decode.field("total_unpaid_blocks", Json_decode.$$int, x),
          /* totalActivatedStake */Json_decode.field("total_activated_stake", BigNumber.decode, x),
          /* threshActivatedStakeTime */Json_decode.field("thresh_activated_stake_time", Eos_Types.TimePoint[/* decode */0], x),
          /* lastProducerScheduleSize */Json_decode.field("last_producer_schedule_size", Json_decode.$$int, x),
          /* totalProducerVoteWeight */Json_decode.field("total_producer_vote_weight", BigNumber.decode, x),
          /* lastNameClose */Json_decode.field("last_name_close", Eos_Types.BlockTimestamp[/* decode */0], x)
        ];
}

var GlobalState = /* module */[/* decode */decode];

var arg = Eos.accountName("eosio");

var arg$1 = Eos.accountName("eosio");

var arg$2 = Eos.tableName("global");

function getGlobalState(param) {
  return (function (param$1, param$2) {
      return Eos.getTableSingleton(param, decode, arg, arg$1, arg$2, param$1, param$2);
    });
}

function decode$1(j) {
  return /* record */[
          /* owner */Json_decode.field("owner", Eos_Types.AccountName[/* decode */0], j),
          /* totalVotes */Json_decode.field("total_votes", BigNumber.decode, j),
          /* producerKey */Json_decode.field("producer_key", Json_decode.string, j),
          /* isActive */Json_decode.field("is_active", (function (param) {
                  return Json_decode.map((function (x) {
                                return x === 1;
                              }), Json_decode.$$int, param);
                }), j),
          /* url */Json_decode.field("url", Json_decode.string, j),
          /* unpaidBlocks */Json_decode.field("unpaid_blocks", Json_decode.$$int, j),
          /* lastClaimTime */Json_decode.field("last_claim_time", Eos_Types.TimePoint[/* decode */0], j),
          /* location */Json_decode.field("location", Json_decode.$$int, j)
        ];
}

function encode(d) {
  var match = d[/* isActive */3];
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "owner",
                Eos_Types.AccountName[/* encode */1](d[/* owner */0])
              ],
              /* :: */[
                /* tuple */[
                  "total_votes",
                  BigNumber.encode(d[/* totalVotes */1])
                ],
                /* :: */[
                  /* tuple */[
                    "producer_key",
                    d[/* producerKey */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "is_active",
                      match ? 1 : 0
                    ],
                    /* :: */[
                      /* tuple */[
                        "url",
                        d[/* url */4]
                      ],
                      /* :: */[
                        /* tuple */[
                          "unpaid_blocks",
                          d[/* unpaidBlocks */5]
                        ],
                        /* :: */[
                          /* tuple */[
                            "last_claim_time",
                            Eos_Types.TimePoint[/* encode */1](d[/* lastClaimTime */6])
                          ],
                          /* :: */[
                            /* tuple */[
                              "location",
                              d[/* location */7]
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var ProducerInfo = /* module */[
  /* decode */decode$1,
  /* encode */encode
];

var arg$3 = Eos.accountName("eosio");

var arg$4 = Eos.accountName("eosio");

var arg$5 = Eos.tableName("producers");

function getProducers(param) {
  return (function (param$1, param$2, param$3, param$4, param$5, param$6) {
      return Eos.getTableRows(param, decode$1, arg$3, arg$4, arg$5, param$1, param$2, param$3, param$4, param$5, param$6);
    });
}

var VoterInfo = /* module */[];

var UserResources = /* module */[];

var DelegatedBandwidth = /* module */[];

var Connector = /* module */[];

var ExchangeState = /* module */[];

var RefundRequest = /* module */[];

var NameBidInfo = /* module */[];

exports.GlobalState = GlobalState;
exports.getGlobalState = getGlobalState;
exports.ProducerInfo = ProducerInfo;
exports.getProducers = getProducers;
exports.VoterInfo = VoterInfo;
exports.UserResources = UserResources;
exports.DelegatedBandwidth = DelegatedBandwidth;
exports.Connector = Connector;
exports.ExchangeState = ExchangeState;
exports.RefundRequest = RefundRequest;
exports.NameBidInfo = NameBidInfo;
/* arg Not a pure module */
